### ISSUE TITLE
TypeError: this.model.getRepository is not a function

### ISSUE THREAD

**Issue by johannb75** [SoftwareBrothers/admin-bro-typeorm#15]
Hello,
I've been using AdminBro with Sequelize for a while now but I wanted to try TypeORM with this library.
I've followed the doc step by step, but I get this error:

>TypeError: this.model.getRepository is not a function
    at Resource.prepareProps (C:\nodejs\test\ORM\typeorm\node_modules\@admin-bro\typeorm\src\Resource.ts:120:36)
    at new Resource (C:\nodejs\test\ORM\typeorm\node_modules\@admin-bro\typeorm\src\Resource.ts:21:29)
    at Database.resources (C:\nodejs\test\ORM\typeorm\node_modules\@admin-bro\typeorm\src\Database.ts:15:22)

Here is my code:
```ts
import "reflect-metadata";

import express from "express";
import { Connection, createConnection } from "typeorm";

import AdminBro from "admin-bro";
import AdminBroExpress from "@admin-bro/express";
import * as AdminBroTypeORM from "@admin-bro/typeorm";

const app = express();
const PORT = process.env.PORT || 8080;

const main = async (connection: Connection) => {
        // init admin bro
	AdminBro.registerAdapter(AdminBroTypeORM);
	const adminBro = new AdminBro({
		databases: [connection],
		rootPath: "/admin",
	});
	const router = AdminBroExpress.buildRouter(adminBro);

        // start express server
	app.use(adminBro.options.rootPath, router);
	app.listen(PORT, () => console.log("Listening on", PORT));
};

createConnection()
	.then(main)
	.catch((error) => console.log(error));
```
Thanks in advance

**Comment by vensauro** [comment]
I too have this error, this is because the Model class use the datamapper aproach and not the active record.
The method https://github.com/SoftwareBrothers/admin-bro-typeorm/blob/7ff78547db5eb0c8344692c92577a973593437d7/src/Resource.ts#L25 `this.model.getRepository()` needs the model to extends the BaseEntity from typeorm

**Comment by derksacklowski** [comment]
I have the same problem. The base implementation without any resources fails with the mentioned issue

**Comment by derksacklowski** [comment]
Is there support for the datamapper approach planned?

**Comment by TPXP** [comment]
I'm having the same issue and worked on a patch circumventing the issue, you can get it here (apply with [patch-package](https://www.npmjs.com/package/patch-package)): https://gist.github.com/TPXP/ac29ad0fbf126b8470858ede6d8b6cdb

I haven't tested it against Data Mapper entities, so take extra care if your project mixes both types of entities.
